apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientyou-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clientyou
  minReadySeconds: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: clientyou
    spec:
      containers:
      - name: clientyou
        image: cianosull/clientyou:latest