apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientred-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clientred
  minReadySeconds: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: clientred
    spec:
      containers:
      - name: clientred
        image: cianosull/clientred:latest